#pragma once

#include "depch.h"
#include "DefinitelyEngine/Core.h"
#include "Collider.h"
#include "Ray.h"

namespace DefinitelyEngine {

    // Overlap result between two colliders.
    // normal points from b toward a (apply +normal to push a away, -normal to push b away).
    struct DEFINITELY_ENGINE_API Contact {
        Collider*  a      = nullptr;
        Collider*  b      = nullptr;
        glm::vec3  normal = { 0.0f, 0.0f, 0.0f };
        float      depth  = 0.0f;
    };

    // Non-owning registry of colliders.
    // Lifetime of each Collider* is managed by the owner (e.g. GameLayer).
    class DEFINITELY_ENGINE_API CollisionWorld {
    public:
        void Register(Collider* collider);
        void Unregister(const std::string& ownerName);
        Collider* Find(const std::string& ownerName) const;
        const std::vector<Collider*>& GetAll() const { return m_Colliders; }

        // Mark a pair of tags whose colliders should never generate contacts.
        // Order of tagA/tagB does not matter. Call before the first Update().
        void IgnoreCollision(const std::string& tagA, const std::string& tagB);

        // Runs capsule-capsule narrow phase and fills GetContacts() for this frame.
        // worldCenter on each Collider must be updated by the caller before invoking this.
        void Update();

        // Contacts generated by the most recent Update() call.
        const std::vector<Contact>& GetContacts() const { return m_Contacts; }

        // Returns true if any collider is hit within maxDist. outHit is only valid on true.
        // If excludeTag is non-empty, colliders with that tag are skipped.
        bool Raycast(const Ray& ray, float maxDist, RaycastHit& outHit, const std::string& excludeTag = "") const;

    private:
        bool ShouldIgnore(const std::string& tagA, const std::string& tagB) const;

        std::vector<Collider*>                          m_Colliders;    // non-owning
        std::vector<std::pair<std::string, std::string>> m_IgnorePairs;
        std::vector<Contact>                            m_Contacts;
    };

}
