# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  Engine_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  Engine_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW Engine Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Engine/external/GLFW -f Makefile config=$(GLFW_config)
endif

Engine: GLFW
ifneq (,$(Engine_config))
	@echo "==== Building Engine ($(Engine_config)) ===="
	@${MAKE} --no-print-directory -C . -f Engine.make config=$(Engine_config)
endif

Sandbox: Engine
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C . -f Sandbox.make config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engine/external/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C . -f Engine.make clean
	@${MAKE} --no-print-directory -C . -f Sandbox.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   Engine"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"